"""Generate the static, properly named font instances the book embeds.

Chrome/Skia writes variable fonts into PDFs as Type 3 glyph procedures, so we
instantiate Source Serif 4 (text opsz 11, display opsz 60) and Inter at fixed
weights. Sources: fonts/src (Google Fonts variable subsets, OFL). Symbols
(→ ✓ ✗ ○) are subset from DejaVu Sans (Bitstream Vera licence).
"""
import re
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

HERE = Path(__file__).parent
SRC, OUT = HERE / "fonts" / "src", HERE / "fonts"
WEIGHT_NAMES = {400: "Regular", 500: "Medium", 600: "Semibold", 700: "Bold", 800: "Extrabold", 900: "Black"}


def rename(font, family, weight, italic):
    style = WEIGHT_NAMES[weight] + ("Italic" if italic and weight != 400 else "")
    style = "Italic" if italic and weight == 400 else style
    ps = f"{family.replace(' ', '')}-{style}"
    names = font["name"]
    names.names = [n for n in names.names if n.nameID > 25 or n.nameID in (0, 7, 8, 9, 11, 12, 13, 14)]
    for nid, val in {1: family if style in ("Regular", "Italic", "Bold", "BoldItalic") else f"{family} {style}",
                     2: style if style in ("Regular", "Italic", "Bold", "BoldItalic") else "Regular",
                     4: f"{family} {style}", 6: ps, 16: family, 17: style}.items():
        names.setName(val, nid, 3, 1, 0x409)


def main():
    css = (SRC / "fonts.css").read_text()
    src = {}
    for sub, body in re.findall(r"/\* (\S+) \*/\s*@font-face \{(.*?)\}", css, re.S):
        if sub in ("latin", "latin-ext"):
            fam = re.search(r"font-family: '(.*?)'", body).group(1)
            st = re.search(r"font-style: (\w+)", body).group(1)
            src[(fam, st, sub)] = (re.search(r"url\((.*?)\)", body).group(1).split("/")[-1],
                                   re.search(r"unicode-range: (.*?);", body).group(1))
    jobs = [("B1 Serif Text", "serif-text", "Source Serif 4", {"opsz": 11}, (400, 600, 700)),
            ("B1 Serif Display", "serif-display", "Source Serif 4", {"opsz": 60}, (400, 600, 700, 900)),
            ("B1 Sans", "sans", "Inter", {}, (400, 500, 600, 700, 800))]
    faces = []
    for css_fam, stem, fam, fixed, weights in jobs:
        variants = [(w, False) for w in weights] + ([(400, True)] if fam == "Source Serif 4" else [])
        for w, italic in variants:
            for sub in ("latin", "latin-ext"):
                file, urange = src[(fam, "italic" if italic else "normal", sub)]
                f = TTFont(SRC / file)
                axes = {a.axisTag for a in f["fvar"].axes}
                limits = {k: v for k, v in {**fixed, "wght": w}.items() if k in axes}
                inst = instancer.instantiateVariableFont(f, limits)
                rename(inst, css_fam, w, italic)
                name = f"{stem}-{w}{'i' if italic else ''}-{sub}.woff2"
                inst.flavor = "woff2"
                inst.save(OUT / name)
                faces.append(f"@font-face {{ font-family: '{css_fam}'; font-style: {'italic' if italic else 'normal'}; "
                             f"font-weight: {w}; font-display: block; src: url(fonts/{name}) format('woff2'); unicode-range: {urange}; }}")
    sym_range = [0x2192, 0x2713, 0x2717, 0x25CB]
    for w, ttf in ((400, "DejaVuSans.ttf"), (700, "DejaVuSans-Bold.ttf")):
        f = TTFont(f"/usr/share/fonts/truetype/dejavu/{ttf}")
        s = subset.Subsetter()
        s.populate(unicodes=sym_range)
        s.subset(f)
        rename(f, "B1 Symbols", w, False)
        f.flavor = "woff2"
        f.save(OUT / f"symbols-{w}.woff2")
        faces.append(f"@font-face {{ font-family: 'B1 Symbols'; font-weight: {w}; font-display: block; "
                     f"src: url(fonts/symbols-{w}.woff2) format('woff2'); unicode-range: U+2192, U+2713, U+2717, U+25CB; }}")
    (HERE / "fonts.css").write_text("/* Generated by make_fonts.py — do not edit. */\n" + "\n".join(faces) + "\n")
    print(len(faces), "faces")


if __name__ == "__main__":
    main()
